apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-service-secrets
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-prod
  target:
    name: my-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: /joga-together/SPRING_DATASOURCE_PASSWORD
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: /joga-together/SPRING_DATASOURCE_USERNAME
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: /joga-together/SPRING_DATASOURCE_URL
    - secretKey: SPRING_MAIL_USERNAME
      remoteRef:
        key: /joga-together/SPRING_MAIL_USERNAME
    - secretKey: SPRING_MAIL_PASSWORD
      remoteRef:
        key: /joga-together/SPRING_MAIL_PASSWORD
