apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-service-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'URL_DO_SEU_REPO_GITOPS' # Ex: https://github.com/jason/platform-gitops.git
    targetRevision: HEAD
    path: apps/my-service/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod-apps
  syncPolicy:
    # Para produção, o sync automático é desabilitado por segurança.
    # A promoção para produção deve ser um passo manual.
    automated: null
    syncOptions:
    - CreateNamespace=true
