apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: mysql
    targetRevision: '9.10.2' # Use uma versão específica do Helm chart
    helm:
      valueFiles:
      - 'values.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod-infra
  syncPolicy:
    # Para produção, o sync automático é desabilitado por segurança.
    automated: null
    syncOptions:
    - CreateNamespace=true
