# platform-gitops/argocd/dev/mysql.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # 1. Aponta para o SEU repo GitOps para encontrar o values.yaml
    repoURL: 'https://github.com/ojasonw/platform-gitops.git'
    targetRevision: HEAD
    path: infra/mysql/dev

    # 2. Especifica o Helm Chart remoto que será usado
    helm:
      valueFiles:
      - values.yaml
      
      # Chart remoto
      chart: mysql
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 9.10.2

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
