apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: dev-apps
      server: https://kubernetes.default.svc
    - namespace: dev-monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
